name: "Feature Request"
description: 기능 제안/개선 요청용 템플릿
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Background
      description: 어떤 문제를 해결하려는지 작성해주세요.
      placeholder: 예) 현재 xx 작업이 수동이라 반복 비용이 큽니다.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: 원하는 해결 방법을 구체적으로 작성해주세요.
      placeholder: 예) yy API를 추가하여 자동화
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: 고려한 대안이 있으면 작성해주세요.

  - type: textarea
    id: scope
    attributes:
      label: Scope / Out of Scope
      description: 범위와 제외 범위를 구분해서 작성해주세요.
      placeholder: |
        - In scope: ...
        - Out of scope: ...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: 완료 기준을 체크리스트 형태로 작성해주세요.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
